CREATE TABLE FoodRecognitionRequests
(
    ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ImgBase64 LONGTEXT,
    ImgType VARCHAR(20),
    Status TINYINT,
    CreateTS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);